# Install ff to read datasets from disk instead of memory
#install.packages("ff")

# Install poLCA to run Latent Class Analysis on polytomous variables
#install.packages("poLCA")

# Load ff and poLCA into workspace
library("ff")
library("poLCA")

fftempdir = "~/GitHub/Btech2018/data/Tempff"

# Chunk load 2001 census data into dataframe from csv file
X2001Census <- read.csv.ffdf(NULL, "~/GitHub/Btech2018/data/Worksheet/2001.Combined.Dataset.normalised.csv")
X2001Census_sub <- X2001Census[setdiff(colnames(X2001Census), c("Ward","B0_TO_4","B5_TO_14","B65_OLDER","C0_TO_4","C5_TO_14","C65_OLDER","I_A0_TO_4","I_A5_TO_14","I_A65_OLDER","W0_TO_4","W5_TO_14","W65_OLDER","BLOWER_CLASS","BWORKING_CLASS","BLOWER_MIDDLE_CLASS","CLOWER_CLASS","CWORKING_CLASS","CLOWER_MIDDLE_CLASS","I_ALOWER_CLASS","I_AWORKING_CLASS","I_ALOWER_MIDDLE_CLASS","WLOWER_CLASS","WWORKING_CLASS","WLOWER_MIDDLE_CLASS","BUNEMPLOYED","CUNEMPLOYED","I_AUNEMPLOYED","WUNEMPLOYED","BSOME_PRIMARY","BCOMPLETED_PRIMAR","BSOME_SECONDARY","BMATRIC","CSOME_PRIMARY","CCOMPLETED_PRIMAR","CSOME_SECONDARY","CMATRIC","I_ASOME_PRIMARY","I_ACOMPLETED_PRIMAR","I_ASOME_SECONDARY","I_AMATRIC","WSOME_PRIMARY","WCOMPLETED_PRIMAR","WSOME_SECONDARY","WMATRIC"))]

func <- cbind(B15_TO_24,B25_TO_64,C15_TO_24,C25_TO_64,I_A15_TO_24,I_A25_TO_64,W15_TO_24,W25_TO_64,BUPPER_MIDDLE_CLASS,BUPPER_CLASS,CUPPER_MIDDLE_CLASS,CUPPER_CLASS,I_AUPPER_MIDDLE_CLASS,I_AUPPER_CLASS,WUPPER_MIDDLE_CLASS,WUPPER_CLASS,BEMPLOYED,CEMPLOYED,I_AEMPLOYED,WEMPLOYED,BHIGHER,BOTHER,CHIGHER,COTHER,I_AHIGHER,I_AOTHER,WHIGHER,WOTHER,BFAMILY,BSINGLE,CFAMILY,CSINGLE,I_AFAMILY,I_ASINGLE,WFAMILY,WSINGLE,B_PERCENT_MALE,C_PERCENT_MALE,I_A_PERCENT_MALE,W_PERCENT_MALE)~1

lca <- poLCA(func, X2001Census_sub, 10,verbose = FALSE)